export const SPECIALTY_PRICES: Record<string, number> = {
  GENERALISTE: 30,
  CARDIOLOGUE: 40,
  DERMATOLOGUE: 35,
  OPHTALMOLOGUE: 45,
  PEDIATRE: 25,
  DENTISTE: 50,
  NEUROLOGUE: 60,
  ORL: 40,
  GASTROENTEROLOGUE: 55,
  RHUMATOLOGUE: 50,
};
